config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #  Creating a route to the index page
  root 'articles#index', as: 'home'

  resources :articles
  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: true
  validates :body, presence:  true
end

app/models/question.rb
class Question < ApplicationRecord

  validates :title, presence: true
  validates :answer, presence:  true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #get all articles
  def index
    @articles = Article.all
  end


  def new
    @article = Article.new
  end


  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if (@article.update(article_params))
      @article.update_attribute(:body, translate_to_ger(params[:article][:body]))
      redirect_to @article
    else
      render 'edit'
    end
  end

  #delete an article
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def create
    @article = Article.new(article_params)
    @article.body = translate_to_ger(params[:article][:body])
    if (@article.save)
      redirect_to @article
    else
      render 'new'
    end

  end

  private def article_params
    params.require(:article).permit(:title, :body)
  end

  #translate text to German
  # source: https://github.com/MicrosoftTranslator/Text-Translation-API-V3-Ruby/blob/master/Translate.rb
  private def translate_to_ger(text)

    if (!ENV["TRANSLATOR_TEXT_SUBSCRIPTION_KEY"])
      raise "Please set/export the following environment variable: TRANSLATOR_TEXT_SUBSCRIPTION_KEY"
    else
      subscription_key = ENV["TRANSLATOR_TEXT_SUBSCRIPTION_KEY"]
    end
    endpoint = 'https://api.cognitive.microsofttranslator.com/translate?api-version=3.0'

    #translate to German
    params = '&to=de'

    uri = URI (endpoint + params)

    content = '[{"Text" : "' + text + '"}]'

    request = Net::HTTP::Post.new(uri)
    request['Content-Type'] = 'application/json'
    request['Content-length'] = content.length
    request['Ocp-Apim-Subscription-Key'] = subscription_key
    request['X-ClientTraceId'] = SecureRandom.uuid
    request.body = content

    response = Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
      http.request (request)
    end

    result = response.body.force_encoding("utf-8")

    json_result = JSON.parse(result)

    begin
      trans_res = json_result[0]['translations'][0]['text']
    rescue *Exception => e
      puts e
    end

    return trans_res
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def show
    @question =Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if(@question.update(question_params))
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  def create
    @question = Question.new(question_params)

    if(@question.save)
      redirect_to @question
    else
      render 'new'
    end
  end

  def question_params
    params.require(:question).permit(:title, :answer)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
    <% if @article.errors.any? %>
      <%@article.errors.full_messages.each  do |msg| %>
       <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'})  %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/articles/index.html.erb
<h1>All articles</h1>
<hr>
<%= link_to "Create article", new_article_path(@article), :class => 'btn btn-primary' %>
<% @articles.each do |article| %>
    <div class="card card-body bg-light">
      <h4> <%= article.title %></h4>
      <%= link_to "View article", article_path(article), :class => 'btn btn-default'%>
    </div>
<% end %>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'})  %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %> </h2>
<p><%= @article.body %> </p>
<hr>
<%= link_to "Edit", edit_article_path(@article), :class => 'btn btn-primary' %>
<%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: 'Are you sure you want do delete this?'},
    :class => 'btn btn-danger' %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KnowledgeBase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="avbar navbar-expand-md navbar-dark bg-dark ">
      <div class="container">
        <div class="navbar-header">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          <a class="navbar-brand" href="#">KnowledgeBase</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Articles", articles_path %></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to "FAQ", questions_path %></li>
          </ul>
        </div><!--/ .nav-collapse -->
      </div>
    </nav>

<div class="container">
     <%= yield %>
  </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to the knowledge base</h1>

app/views/questions/edit.html.erb
<h1>Edit question</h1>
<%= form_for :question, url: question_path(@question), method: :patch do |f| %>
  <% if @question.errors.any? %>
    <%@question.errors.full_messages.each  do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :answer %><br>
    <%= f.text_area(:answer, {:class => 'form-control'})  %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/questions/index.html.erb
<h1>FAQ</h1>
<hr>
<%= link_to "Create question", new_question_path(@question), :class => 'btn btn-primary' %>
<% @questions.each do |question| %>
  <div class="card card-body bg-light">
    <h4><%= question.title%></h4>
    <p><%= question.answer %></p>
    <%= link_to "Edit", question_path(question), :class => 'btn btn-default'%>
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>Create a question</h1>
<%= form_for :question, url: questions_path do |f| %>
  <% if @question.errors.any? %>
    <%@question.errors.full_messages.each  do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :answer %><br>
    <%= f.text_area(:answer, {:class => 'form-control'})  %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/questions/show.html.erb
<h2><%= @question.title %> </h2>
<p><%= @question.answer %> </p>
<hr>
<%= link_to "Edit", edit_question_path(@question), :class => 'btn btn-primary' %>
<%= link_to "Delete", question_path(@question), method: :delete, data: {confirm: 'Are you sure you want do delete this?'},
            :class => 'btn btn-danger' %>